BEGIN;
UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=130;
DELETE FROM layers_layer_styles WHERE layer_id=130;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 130, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=131;
DELETE FROM layers_layer_styles WHERE layer_id=131;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 362 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 131, 333 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=132;
DELETE FROM layers_layer_styles WHERE layer_id=132;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 132, 362 );

UPDATE layers_layer SET default_style_id=0 WHERE resourcebase_ptr_id=393;
DELETE FROM layers_layer_styles WHERE layer_id=393;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 393, 540 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=320;
DELETE FROM layers_layer_styles WHERE layer_id=320;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 362 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 320, 548 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=321;
DELETE FROM layers_layer_styles WHERE layer_id=321;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 321, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=347;
DELETE FROM layers_layer_styles WHERE layer_id=347;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 347, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=348;
DELETE FROM layers_layer_styles WHERE layer_id=348;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 348, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=323;
DELETE FROM layers_layer_styles WHERE layer_id=323;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 323, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=324;
DELETE FROM layers_layer_styles WHERE layer_id=324;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 324, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=353;
DELETE FROM layers_layer_styles WHERE layer_id=353;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 353, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=354;
DELETE FROM layers_layer_styles WHERE layer_id=354;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 354, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=350;
DELETE FROM layers_layer_styles WHERE layer_id=350;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 350, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=351;
DELETE FROM layers_layer_styles WHERE layer_id=351;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 351, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=349;
DELETE FROM layers_layer_styles WHERE layer_id=349;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 349, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=319;
DELETE FROM layers_layer_styles WHERE layer_id=319;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 319, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=346;
DELETE FROM layers_layer_styles WHERE layer_id=346;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 346, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=352;
DELETE FROM layers_layer_styles WHERE layer_id=352;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 352, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=322;
DELETE FROM layers_layer_styles WHERE layer_id=322;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 322, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=15;
DELETE FROM layers_layer_styles WHERE layer_id=15;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 15, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=16;
DELETE FROM layers_layer_styles WHERE layer_id=16;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 16, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=18;
DELETE FROM layers_layer_styles WHERE layer_id=18;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 18, 362 );

UPDATE layers_layer SET default_style_id=347 WHERE resourcebase_ptr_id=17;
DELETE FROM layers_layer_styles WHERE layer_id=17;
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 331 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 356 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 357 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 358 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 359 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 360 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 361 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 330 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 363 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 332 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 333 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 334 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 365 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 368 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 369 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 370 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 366 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 364 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 347 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 367 );
INSERT INTO layers_layer_styles ( layer_id, style_id ) VALUES ( 17, 362 );

COMMIT;