var examples = [
	{
		"_id": 904,
		"invisibleAttrs": [],
		"invisibleYears": [],
		"title": "Neighbours",
		"type": "columnchart",
		"attrs": [{
			"as": 31,
			"attr": 16,
			"normType": null,
			"normAs": null,
			"normAttr": null,
			"normYear": "",
			"attrNameNormalized": "",
			"checked": true,
			"numCategories": "",
			"classType": "",
			"zeroesAsNull": "",
			"name": "",
			"topic": "",
			"parentId": null,
			"index": 0,
			"depth": 0,
			"expanded": false,
			"expandable": true,
			"leaf": false,
			"cls": "",
			"iconCls": "",
			"icon": "",
			"root": false,
			"isLast": false,
			"isFirst": false,
			"allowDrop": true,
			"allowDrag": true,
			"loaded": false,
			"loading": false,
			"href": "",
			"hrefTarget": "",
			"qtip": "",
			"qtitle": "",
			"children": null,
			"attrName": "Neighbours in 5km",
			"asName": "Neighbours in 5km",
			"treeNodeText": "Neighbours in 5km"
		}, {
			"as": 32,
			"attr": 15,
			"normType": null,
			"normAs": null,
			"normAttr": null,
			"normYear": "",
			"attrNameNormalized": "",
			"checked": true,
			"numCategories": "",
			"classType": "",
			"zeroesAsNull": "",
			"name": "",
			"topic": "",
			"parentId": null,
			"index": 0,
			"depth": 0,
			"expanded": false,
			"expandable": true,
			"leaf": false,
			"cls": "",
			"iconCls": "",
			"icon": "",
			"root": false,
			"isLast": false,
			"isFirst": false,
			"allowDrop": true,
			"allowDrag": true,
			"loaded": false,
			"loading": false,
			"href": "",
			"hrefTarget": "",
			"qtip": "",
			"qtitle": "",
			"children": null,
			"attrName": "Primary Neighbours in 5km",
			"asName": "Primary neighbours in 5 km",
			"treeNodeText": "Primary Neighbours in 5km"
		}, {
			"as": 33,
			"attr": 17,
			"normType": null,
			"normAs": null,
			"normAttr": null,
			"normYear": "",
			"attrNameNormalized": "",
			"checked": true,
			"numCategories": "",
			"classType": "",
			"zeroesAsNull": "",
			"name": "",
			"topic": "",
			"parentId": null,
			"index": 0,
			"depth": 0,
			"expanded": false,
			"expandable": true,
			"leaf": false,
			"cls": "",
			"iconCls": "",
			"icon": "",
			"root": false,
			"isLast": false,
			"isFirst": false,
			"allowDrop": true,
			"allowDrag": true,
			"loaded": false,
			"loading": false,
			"href": "",
			"hrefTarget": "",
			"qtip": "",
			"qtitle": "",
			"children": null,
			"attrName": "Secondary neighbours in 5 km",
			"asName": "Secondary neighbours in 5km ",
			"treeNodeText": "Secondary neighbours in 5 km"
		}],
		"featureLayerOpacity": "70",
		"classType": "quantiles",
		"numCategories": "5",
		"constrainFl": [0, 3],
		"stacking": "none",
		"chartId": 6599186,
		"areas": {"70": {"4": ["BE10", "BE31", "BE32", "BE33", "BE34", "BE35", "BE21", "BE22", "BE23", "BE24", "BE25"]}},
		"years": [6],
		"start": 0,
		"limit": 15,
		"sort": null,
		"selectedAreas": "[{\"70\":{\"2\":[\"BE\"],\"3\":[\"BE2\"],\"4\":[\"BE31\",\"BE32\",\"BE24\"]},\"71\":{\"3\":[\"ITC\"]}}]",
		"defSelectedArea": "null",
		"colorMap": {
			"70": {
				"2": {"BE": "34ea81"},
				"3": {"BE2": "34ea81"},
				"4": {"BE31": "34ea81", "BE32": "34ea81", "BE24": "34ea81"}
			}, "71": {"3": {"ITC": "34ea81"}}
		},
		"created": ISODate("2016-07-26T06:31:23.168Z"),
		"createdBy": 2,
		"changed": ISODate("2016-07-26T06:31:23.970Z"),
		"changedBy": null
	},
	{
		"_id": 905,
		"layers": [{
			"type": "selectedareasfilled",
			"opacity": 0.7,
			"name": "Selected areas filled",
			"legendSrc": "",
			"stylesParam": "",
			"sld": {
				"sld": "<sld:StyledLayerDescriptor xmlns:sld=\"http://www.opengis.net/sld\" version=\"1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd\" xmlns:ogc=\"http://www.opengis.net/ogc\" xmlns:gml=\"http://www.opengis.net/gml\"><sld:Name>style</sld:Name><sld:Title>Style</sld:Title><sld:NamedLayer><sld:Name>puma:layer_76</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MaxScaleDenominator>10000000</sld:MaxScaleDenominator><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer><sld:TextSymbolizer><sld:Label><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">name</ogc:PropertyName></sld:Label><sld:Font><sld:CssParameter name=\"font-family\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">DejaVu Sans Condensed</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-size\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">12</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-weight\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">bold</ogc:Literal></sld:CssParameter></sld:Font><sld:LabelPlacement><sld:PointPlacement><sld:AnchorPoint><sld:AnchorPointX>0.5</sld:AnchorPointX><sld:AnchorPointY>0.5</sld:AnchorPointY></sld:AnchorPoint></sld:PointPlacement></sld:LabelPlacement></sld:TextSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MinScaleDenominator>10000000</sld:MinScaleDenominator><sld:PointSymbolizer><sld:Graphic><sld:Mark><sld:WellKnownName>circle</sld:WellKnownName><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:Mark><sld:Size><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">8</ogc:Literal></sld:Size></sld:Graphic><sld:Geometry><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">centroid</ogc:PropertyName></sld:Geometry></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer><sld:NamedLayer><sld:Name>puma:layer_78</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE2</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MaxScaleDenominator>10000000</sld:MaxScaleDenominator><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE2</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer><sld:TextSymbolizer><sld:Label><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">name</ogc:PropertyName></sld:Label><sld:Font><sld:CssParameter name=\"font-family\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">DejaVu Sans Condensed</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-size\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">12</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-weight\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">bold</ogc:Literal></sld:CssParameter></sld:Font><sld:LabelPlacement><sld:PointPlacement><sld:AnchorPoint><sld:AnchorPointX>0.5</sld:AnchorPointX><sld:AnchorPointY>0.5</sld:AnchorPointY></sld:AnchorPoint></sld:PointPlacement></sld:LabelPlacement></sld:TextSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE2</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MinScaleDenominator>10000000</sld:MinScaleDenominator><sld:PointSymbolizer><sld:Graphic><sld:Mark><sld:WellKnownName>circle</sld:WellKnownName><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE2</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:Mark><sld:Size><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">8</ogc:Literal></sld:Size></sld:Graphic><sld:Geometry><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">centroid</ogc:PropertyName></sld:Geometry></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer><sld:NamedLayer><sld:Name>puma:layer_80</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE32</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE24</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MaxScaleDenominator>10000000</sld:MaxScaleDenominator><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal><ogc:Literal>BE32</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal><ogc:Literal>BE24</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer><sld:TextSymbolizer><sld:Label><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">name</ogc:PropertyName></sld:Label><sld:Font><sld:CssParameter name=\"font-family\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">DejaVu Sans Condensed</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-size\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">12</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-weight\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">bold</ogc:Literal></sld:CssParameter></sld:Font><sld:LabelPlacement><sld:PointPlacement><sld:AnchorPoint><sld:AnchorPointX>0.5</sld:AnchorPointX><sld:AnchorPointY>0.5</sld:AnchorPointY></sld:AnchorPoint></sld:PointPlacement></sld:LabelPlacement></sld:TextSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE32</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE24</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MinScaleDenominator>10000000</sld:MinScaleDenominator><sld:PointSymbolizer><sld:Graphic><sld:Mark><sld:WellKnownName>circle</sld:WellKnownName><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal><ogc:Literal>BE32</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal><ogc:Literal>BE24</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:Mark><sld:Size><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">8</ogc:Literal></sld:Size></sld:Graphic><sld:Geometry><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">centroid</ogc:PropertyName></sld:Geometry></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer><sld:NamedLayer><sld:Name>puma:layer_94</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>ITC</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MaxScaleDenominator>10000000</sld:MaxScaleDenominator><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>ITC</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer><sld:TextSymbolizer><sld:Label><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">name</ogc:PropertyName></sld:Label><sld:Font><sld:CssParameter name=\"font-family\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">DejaVu Sans Condensed</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-size\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">12</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"font-weight\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">bold</ogc:Literal></sld:CssParameter></sld:Font><sld:LabelPlacement><sld:PointPlacement><sld:AnchorPoint><sld:AnchorPointX>0.5</sld:AnchorPointX><sld:AnchorPointY>0.5</sld:AnchorPointY></sld:AnchorPoint></sld:PointPlacement></sld:LabelPlacement></sld:TextSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>ITC</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or></ogc:Filter><sld:MinScaleDenominator>10000000</sld:MinScaleDenominator><sld:PointSymbolizer><sld:Graphic><sld:Mark><sld:WellKnownName>circle</sld:WellKnownName><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Recode\"><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>ITC</ogc:Literal><ogc:Literal>#34ea81</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:Mark><sld:Size><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">8</ogc:Literal></sld:Size></sld:Graphic><sld:Geometry><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">centroid</ogc:PropertyName></sld:Geometry></sld:PointSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer></sld:StyledLayerDescriptor>",
				"legendSld": ""
			}
		}, {
			"type": "chartlayer",
			"opacity": 0.7,
			"name": "Secondary neighbours in 5 km - Secondary neighbours in 5km ",
			"legendSrc": "http://urban-tep.gisat.cz/api/proxy/wms?REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&WIDTH=50&USE_SECOND=true&LAYER=puma%3Alayer_80&SLD_ID=1aoiu38p41ule",
			"stylesParam": "",
			"sld": {
				"sld": "<sld:StyledLayerDescriptor xmlns:sld=\"http://www.opengis.net/sld\" version=\"1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd\" xmlns:ogc=\"http://www.opengis.net/ogc\" xmlns:gml=\"http://www.opengis.net/gml\"><sld:Name>style</sld:Name><sld:Title>Style</sld:Title><sld:NamedLayer><sld:Name>puma:layer_80</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:And><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE10</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE32</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE33</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE34</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE35</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE21</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE22</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE23</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE24</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE25</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or><ogc:And><ogc:PropertyIsNotEqualTo><ogc:PropertyName>as_33_attr_17</ogc:PropertyName><ogc:Literal>0</ogc:Literal></ogc:PropertyIsNotEqualTo><ogc:Not><ogc:PropertyIsNull><ogc:PropertyName>as_33_attr_17</ogc:PropertyName></ogc:PropertyIsNull></ogc:Not></ogc:And></ogc:And></ogc:Filter><sld:MaxScaleDenominator>100000000</sld:MaxScaleDenominator><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Categorize\"><ogc:Mul><ogc:PropertyName>as_33_attr_17</ogc:PropertyName><ogc:Literal>1</ogc:Literal></ogc:Mul><ogc:Literal>#f2f2ff</ogc:Literal><ogc:Literal>11.56</ogc:Literal><ogc:Literal>#b6b6e6</ogc:Literal><ogc:Literal>12.67</ogc:Literal><ogc:Literal>#7979cc</ogc:Literal><ogc:Literal>14.61</ogc:Literal><ogc:Literal>#3d3db3</ogc:Literal><ogc:Literal>15.71</ogc:Literal><ogc:Literal>#000099</ogc:Literal></ogc:Function></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:And><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE10</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE32</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE33</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE34</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE35</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE21</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE22</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE23</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE24</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE25</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or><ogc:And><ogc:PropertyIsNotEqualTo><ogc:PropertyName>as_33_attr_17</ogc:PropertyName><ogc:Literal>0</ogc:Literal></ogc:PropertyIsNotEqualTo><ogc:Not><ogc:PropertyIsNull><ogc:PropertyName>as_33_attr_17</ogc:PropertyName></ogc:PropertyIsNull></ogc:Not></ogc:And></ogc:And></ogc:Filter><sld:MinScaleDenominator>100000000</sld:MinScaleDenominator><sld:PointSymbolizer><sld:Graphic><sld:Mark><sld:WellKnownName>square</sld:WellKnownName><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Function xmlns:ogc=\"http://www.opengis.net/ogc\" name=\"Categorize\"><ogc:Mul><ogc:PropertyName>as_33_attr_17</ogc:PropertyName><ogc:Literal>1</ogc:Literal></ogc:Mul><ogc:Literal>#f2f2ff</ogc:Literal><ogc:Literal>11.56</ogc:Literal><ogc:Literal>#b6b6e6</ogc:Literal><ogc:Literal>12.67</ogc:Literal><ogc:Literal>#7979cc</ogc:Literal><ogc:Literal>14.61</ogc:Literal><ogc:Literal>#3d3db3</ogc:Literal><ogc:Literal>15.71</ogc:Literal><ogc:Literal>#000099</ogc:Literal></ogc:Function></sld:CssParameter><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#222222</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:Mark><sld:Size><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">18</ogc:Literal></sld:Size></sld:Graphic><sld:Geometry><ogc:PropertyName xmlns:ogc=\"http://www.opengis.net/ogc\">centroid</ogc:PropertyName></sld:Geometry></sld:PointSymbolizer></sld:Rule><sld:Rule><ogc:Filter xmlns:ogc=\"http://www.opengis.net/ogc\"><ogc:And><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE10</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE31</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE32</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE33</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE34</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE35</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE21</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE22</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE23</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE24</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsEqualTo><ogc:PropertyName>gid</ogc:PropertyName><ogc:Literal>BE25</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Or><ogc:Or><ogc:PropertyIsEqualTo><ogc:PropertyName>as_33_attr_17</ogc:PropertyName><ogc:Literal>0</ogc:Literal></ogc:PropertyIsEqualTo><ogc:PropertyIsNull><ogc:PropertyName>as_33_attr_17</ogc:PropertyName></ogc:PropertyIsNull></ogc:Or></ogc:And></ogc:Filter><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#bbbbbb</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer></sld:StyledLayerDescriptor>",
				"legendSld": "<sld:StyledLayerDescriptor xmlns:sld=\"http://www.opengis.net/sld\" version=\"1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://www.opengis.net/sld http://schemas.opengis.net/sld/1.0.0/StyledLayerDescriptor.xsd \" xmlns:ogc=\"http://www.opengis.net/ogc\" xmlns:gml=\"http://www.opengis.net/gml\"><sld:Name>style</sld:Name><sld:Title>Style</sld:Title><sld:NamedLayer><sld:Name>puma:layer_80</sld:Name><sld:UserStyle><sld:FeatureTypeStyle><sld:Rule><sld:Name></sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke-opacity\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">0</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><sld:Name>&lt; 11.56</sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#f2f2ff</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><sld:Name>11.56â€”12.67</sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#b6b6e6</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><sld:Name>12.67â€”14.61</sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#7979cc</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><sld:Name>14.61â€”15.71</sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#3d3db3</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule><sld:Rule><sld:Name>&gt; 15.71</sld:Name><sld:PolygonSymbolizer><sld:Fill><sld:CssParameter name=\"fill\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000099</ogc:Literal></sld:CssParameter></sld:Fill><sld:Stroke><sld:CssParameter name=\"stroke\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">#000000</ogc:Literal></sld:CssParameter><sld:CssParameter name=\"stroke-width\"><ogc:Literal xmlns:ogc=\"http://www.opengis.net/ogc\">1</ogc:Literal></sld:CssParameter></sld:Stroke></sld:PolygonSymbolizer></sld:Rule></sld:FeatureTypeStyle></sld:UserStyle></sld:NamedLayer></sld:StyledLayerDescriptor>"
			}
		}, {
			"type": "topiclayer",
			"opacity": 0.7,
			"name": "Global Settlements Inventory",
			"legendSrc": "http://urban-tep.gisat.cz/api/proxy/wms?LAYERS=geonode%3Abel_75m_binconnectivity_10km_5km_3km_2_km_1km_1&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&WIDTH=50",
			"layersParam": "geonode:bel_75m_binconnectivity_10km_5km_3km_2_km_1km_1,geonode:che_75m_binconnectivity_10km_5km_3km_2_km_1km,geonode:cze_75m_binconnectivity_10km_5km_3km_2_km_1km,geonode:ita_75m_binconnectivity_10km_5km_3km_2_km_1km,geonode:lie_75m_binconnectivity_10km_5km_3km_2_km_1km,geonode:lux_75m_binconnectivity_10km_5km_3km_2_km_1km",
			"stylesParam": ",,,,,"
		}, {"type": "osm", "opacity": 1, "name": "OpenStreetMap", "legendSrc": ""}],
		"layers2": null,
		"type": "map",
		"trafficLayer": false,
		"year": 6,
		"yearName": "2012",
		"year2": null,
		"year2Name": null,
		"center": {"lon": 457125.52976074, "lat": 6507698.6416423},
		"size": {"w": 1247, "h": 875},
		"zoom": 8,
		"created": ISODate("2016-07-26T06:34:39.963Z"),
		"createdBy": 2,
		"changed": ISODate("2016-07-26T06:43:11.131Z"),
		"changedBy": 2
	}

];