var examples = [
	{
		"_id": 1951,
		"name": "",
		"conf": {
			"multipleMaps": false,
			"years": [6],
			"dataset": 1,
			"theme": 11,
			"visualization": 909,
			"location": 70,
			"expanded": {"70": {"2": ["BE"]}},
			"selMap": {"ff4c39": []},
			"choroplethCfg": [{
				"as": 31,
				"attr": 16,
				"normType": null,
				"normAs": null,
				"normAttr": null,
				"normYear": "",
				"attrNameNormalized": "",
				"checked": true,
				"numCategories": 5,
				"classType": "quantiles",
				"zeroesAsNull": true,
				"name": "",
				"topic": "",
				"parentId": null,
				"index": 0,
				"depth": 0,
				"expanded": false,
				"expandable": true,
				"leaf": false,
				"cls": "",
				"iconCls": "",
				"icon": "",
				"root": false,
				"isLast": false,
				"isFirst": false,
				"allowDrop": true,
				"allowDrag": true,
				"loaded": false,
				"loading": false,
				"href": "",
				"hrefTarget": "",
				"qtip": "",
				"qtitle": "",
				"children": null,
				"attrName": "Neighbours in 5km",
				"asName": "Neighbours in 5km",
				"treeNodeText": "Neighbours in 5km"
			}, {
				"as": 32,
				"attr": 15,
				"normType": null,
				"normAs": null,
				"normAttr": null,
				"normYear": "",
				"attrNameNormalized": "",
				"checked": true,
				"numCategories": 5,
				"classType": "quantiles",
				"zeroesAsNull": true,
				"name": "",
				"topic": "",
				"parentId": null,
				"index": 0,
				"depth": 0,
				"expanded": false,
				"expandable": true,
				"leaf": false,
				"cls": "",
				"iconCls": "",
				"icon": "",
				"root": false,
				"isLast": false,
				"isFirst": false,
				"allowDrop": true,
				"allowDrag": true,
				"loaded": false,
				"loading": false,
				"href": "",
				"hrefTarget": "",
				"qtip": "",
				"qtitle": "",
				"children": null,
				"attrName": "Primary Neighbours in 5km",
				"asName": "Primary neighbours in 5 km",
				"treeNodeText": "Primary Neighbours in 5km"
			}, {
				"as": 33,
				"attr": 17,
				"normType": null,
				"normAs": null,
				"normAttr": null,
				"normYear": "",
				"attrNameNormalized": "",
				"checked": true,
				"numCategories": 5,
				"classType": "quantiles",
				"zeroesAsNull": true,
				"name": "",
				"topic": "",
				"parentId": null,
				"index": 0,
				"depth": 0,
				"expanded": false,
				"expandable": true,
				"leaf": false,
				"cls": "",
				"iconCls": "",
				"icon": "",
				"root": false,
				"isLast": false,
				"isFirst": false,
				"allowDrop": true,
				"allowDrag": true,
				"loaded": false,
				"loading": false,
				"href": "",
				"hrefTarget": "",
				"qtip": "",
				"qtitle": "",
				"children": null,
				"attrName": "Secondary neighbours in 5 km",
				"asName": "Secondary neighbours in 5km ",
				"treeNodeText": "Secondary neighbours in 5 km"
			}, {
				"as": 34,
				"attr": 18,
				"normType": null,
				"normAs": null,
				"normAttr": null,
				"normYear": "",
				"attrNameNormalized": "",
				"checked": true,
				"numCategories": 5,
				"classType": "quantiles",
				"zeroesAsNull": true,
				"name": "",
				"topic": "",
				"parentId": null,
				"index": 0,
				"depth": 0,
				"expanded": false,
				"expandable": true,
				"leaf": false,
				"cls": "",
				"iconCls": "",
				"icon": "",
				"root": false,
				"isLast": false,
				"isFirst": false,
				"allowDrop": true,
				"allowDrag": true,
				"loaded": false,
				"loading": false,
				"href": "",
				"hrefTarget": "",
				"qtip": "",
				"qtitle": "",
				"children": null,
				"attrName": "Local betweeness",
				"asName": "Local Betweeness",
				"treeNodeText": "Local betweeness"
			}, {
				"as": 35,
				"attr": 19,
				"normType": null,
				"normAs": null,
				"normAttr": null,
				"normYear": "",
				"attrNameNormalized": "",
				"checked": true,
				"numCategories": 5,
				"classType": "quantiles",
				"zeroesAsNull": true,
				"name": "",
				"topic": "",
				"parentId": null,
				"index": 0,
				"depth": 0,
				"expanded": false,
				"expandable": true,
				"leaf": false,
				"cls": "",
				"iconCls": "",
				"icon": "",
				"root": false,
				"isLast": false,
				"isFirst": false,
				"allowDrop": true,
				"allowDrag": true,
				"loaded": false,
				"loading": false,
				"href": "",
				"hrefTarget": "",
				"qtip": "",
				"qtitle": "",
				"children": null,
				"attrName": "Nearest neighbors distances",
				"asName": "Nearest 3 neighbours distance",
				"treeNodeText": "Nearest neighbors distances"
			}],
			"pagingUseSelected": false,
			"pagingSelectedColors": ["ff4c39", "34ea81", "39b0ff", "ffde58", "5c6d7e", "d97dff"],
			"filterMap": {},
			"filterActive": false,
			"layers": [{
				"opacity": 0.7,
				"sortIndex": 0,
				"type": "selectedareasfilled",
				"attributeSet": "",
				"attribute": "",
				"at": "",
				"symbologyId": ""
			}, {
				"opacity": 0.7,
				"sortIndex": 1,
				"type": "areaoutlines",
				"attributeSet": "",
				"attribute": "",
				"at": "",
				"symbologyId": ""
			}, {
				"opacity": 0.7,
				"sortIndex": 2,
				"type": "topiclayer",
				"attributeSet": "",
				"attribute": "",
				"at": 8,
				"symbologyId": "#blank#"
			}, {
				"opacity": 1,
				"sortIndex": 10000,
				"type": "terrain",
				"attributeSet": "",
				"attribute": "",
				"at": "",
				"symbologyId": ""
			}],
			"trafficLayer": false,
			"page": 1,
			"mapCfg": {"center": {"lon": 431719.24913438, "lat": 6541173.6227103}, "zoom": 8},
			"cfgs": [{
				"cfg": {
					"title": "Population",
					"type": "columnchart",
					"attrs": [{
						"as": 12,
						"attr": 13,
						"normType": "area",
						"normAs": "",
						"normAttr": "",
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Total population",
						"asName": "Population",
						"treeNodeText": "Total population"
					}],
					"featureLayerOpacity": "70",
					"classType": "quantiles",
					"numCategories": "5",
					"constrainFl": [0, 3],
					"stacking": "none",
					"chartId": 8966996
				}, "queryCfg": {"invisibleAttrs": [], "invisibleYears": []}
			}, {
				"cfg": {
					"title": "Share of primary and secondary",
					"type": "piechart",
					"attrs": [{
						"as": 32,
						"attr": 15,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Primary Neighbours in 5km",
						"asName": "Primary neighbours in 5 km",
						"treeNodeText": "Primary Neighbours in 5km"
					}, {
						"as": 33,
						"attr": 17,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Secondary neighbours in 5 km",
						"asName": "Secondary neighbours in 5km ",
						"treeNodeText": "Secondary neighbours in 5 km"
					}],
					"featureLayerOpacity": "70",
					"classType": "quantiles",
					"numCategories": "5",
					"constrainFl": [0, 3],
					"stacking": "none",
					"chartId": 7587251
				}, "queryCfg": {"invisibleAttrs": [], "invisibleYears": []}
			}, {
				"cfg": {
					"title": "Dependency between primary neighbours and population",
					"type": "scatterchart",
					"attrs": [{
						"as": 12,
						"attr": 13,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Total population",
						"asName": "Population",
						"treeNodeText": "Total population"
					}, {
						"as": 31,
						"attr": 16,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Neighbours in 5km",
						"asName": "Neighbours in 5km",
						"treeNodeText": "Neighbours in 5km"
					}],
					"featureLayerOpacity": "70",
					"classType": "quantiles",
					"numCategories": "5",
					"constrainFl": [0, 3],
					"stacking": "none",
					"chartId": 2834324
				}, "queryCfg": {"invisibleAttrs": [], "invisibleYears": []}
			}, {
				"cfg": {
					"title": "Neighbours",
					"type": "columnchart",
					"attrs": [{
						"as": 31,
						"attr": 16,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Neighbours in 5km",
						"asName": "Neighbours in 5km",
						"treeNodeText": "Neighbours in 5km"
					}, {
						"as": 32,
						"attr": 15,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Primary Neighbours in 5km",
						"asName": "Primary neighbours in 5 km",
						"treeNodeText": "Primary Neighbours in 5km"
					}, {
						"as": 33,
						"attr": 17,
						"normType": null,
						"normAs": null,
						"normAttr": null,
						"normYear": "",
						"attrNameNormalized": "",
						"checked": true,
						"numCategories": "",
						"classType": "",
						"zeroesAsNull": "",
						"name": "",
						"topic": "",
						"parentId": null,
						"index": 0,
						"depth": 0,
						"expanded": false,
						"expandable": true,
						"leaf": false,
						"cls": "",
						"iconCls": "",
						"icon": "",
						"root": false,
						"isLast": false,
						"isFirst": false,
						"allowDrop": true,
						"allowDrag": true,
						"loaded": false,
						"loading": false,
						"href": "",
						"hrefTarget": "",
						"qtip": "",
						"qtitle": "",
						"children": null,
						"attrName": "Secondary neighbours in 5 km",
						"asName": "Secondary neighbours in 5km ",
						"treeNodeText": "Secondary neighbours in 5 km"
					}],
					"featureLayerOpacity": "70",
					"classType": "quantiles",
					"numCategories": "5",
					"constrainFl": [0, 3],
					"stacking": "none",
					"chartId": 6599186
				}, "queryCfg": {"invisibleAttrs": [], "invisibleYears": []}
			}]
		},
		"created": ISODate("2016-09-05T11:49:10.080Z"),
		"createdBy": 1,
		"changed": ISODate("2016-09-05T11:49:10.080Z"),
		"changedBy": 1
	}
];